authappliance/lib/appliance.py
authappliance/pi-appliance

This depends on https://github.com/privacyidea/mysqlparser/pull/1

Fix redundancy setup and removal

---

authappliance/lib/appliance.py
authappliance/pi-appliance

I think this is a good idea in case the backup/restore fails for whatever reason.

Backup/Restore: Give user feedback about success

---

authappliance/lib/appliance.py
authappliance/pi-appliance

All those services are restarted when the user exits
the appliance tool.
Closes #29
Closes #30

Collect services that need to be restarted

---

authappliance/lib/appliance.py
authappliance/lib/extdialog.py
authappliance/lib/ldap_proxy.py
authappliance/pi-appliance
debian/control
requirements.txt

Should fix #28 for now.
Hmm, sadly this is a lot of code and also includes a lot of refactoring ... :-/

Integrate LDAP Proxy

---

authappliance/menu.py

Show redundancy status

---

.gitmodules
authappliance/lib/utils.py
authappliance/menu.py
test/configure_tinc.py
test/mockdialog.py

This still misses some functionality:
* The user cannot choose the VPN subnet yet
* The user cannot choose the net name yet
But as the main functionality is already working, I thought this would be a good opportunity for a PR. :)

Optionally set up a tinc tunnel between the two replication peers

---

debian/control

When installing pi-appliance we will also install tinc.
Working on #45

We require tinc to be installed.

---

authappliance/menu.py

Let user choose the tinc subnet

---

authappliance/lib/appliance.py
authappliance/lib/utils.py
authappliance/menu.py

1dcfb12 uses the new crontab API to simplify the handling of audit + backup cronjobs.
b651fc4 improves the redundancy setup: We now use the ``execute_ssh_command_and_wait`` function to ensure that we wait for the completion of commands executed remotely. This could even help with occasional delays during redundancy setup (which might happen because the MySQL server takes some time to come up again and we run into some kind of timeout?).

Some refactoring, using the new crontab API

---

authappliance/menu.py

Add possibility to remove tinc tunnel

---

authappliance/lib/updates.py
authappliance/menu.py

Add menu to manage automatic update cronjobs

---

authappliance/lib/ldap_proxy.py
debian/control
requirements.txt

Remove dbus-python dependency

---

authappliance/menu.py

Redundancy setup now asks the user if the FreeRADIUS configuration should be copied to the remote peer.
If the user chooses yes, we copy ``/etc/privacyidea/rlm_perl.ini`` and ``/etc/freeradius/clients.conf`` to the remote peer.
Open questions:
Should we copy the entire ``/etc/freeradius`` directory?
In particular, the appliance tool allows the user to enable and disable FreeRADIUS sites (realized by symlinks in ``/etc/freeradius/sites-enabled``). But with this PR, the redundancy setup tool currently does not copy the enabled and disabled sites to the remote peer. Should we add this feature?
Working on #55

Redundancy setup: Copy FreeRADIUS config

---

authappliance/menu.py

I introduced this one in #61. Whoops :)
Closes #65

Fix last occurrence of deprecated DIALOG_OK

---

.travis.yml

Remove dbus dependency from travis config
Fixes #74

Update crontab parser to allow slash in times

---

authappliance/lib/appliance.py

The parser is already up to date, now we need to use the correct
configuration path.
Fixes #66

Enable FreeRADIUS 3

---

authappliance/lib/ldap_proxy.py
authappliance/menu.py

Add encoding utf8 to Popen calls

---

authappliance/menu.py

When establishing a database replication, the appliance allows to sync the
freeRADIUS configuration as well. Since the paths for freeRADIUS 2.x were
hard-coded, this failed with ubuntu 18.04 and freeRADIUS 3.0.
This adds the syncing of the freeRADIUS 3.0 configuration as well.
Fixes #89

Enable freeRADIUS 3 syncing

---

authappliance/menu.py

add needed "ssl require, user and certificate" to menu.py

Fix focal replication

---

authappliance/menu.py

Use systectl enable/disable for tinc
